languageCode = "en-us"
title = "Ninja Programming Language - Documentation"
baseURL = "/"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Github"
    url = "https://github.com/gravataLonga/ninja"
    weight = 3

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Ninja Programming Language is a general purpose language'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Ninja Programming Language is a general purpose language built by Jonathan Fontes."
    meta_og_title = "Ninja Programming Language"
    meta_og_type = "website"
    meta_og_url = "https://ninja.jonathan.pt"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Ninja Programming Language is a general purpose language built by Jonathan Fontes."
    meta_twitter_card = "summary"
    meta_twitter_site = "@gravataLonga"
    meta_twitter_creator = "@gravataLonga"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
